# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9cd4ff8da1f8bdc1d975bb7c554c2882939dff6caf69285310da451b29b9aa688fe6809102905ce231961ea1ea940443e37e36da209973ec3f7bbdcb0b90583

test:
  secret_key_base: 49625c947de8d89a6c16285697f9a0df4d1ca5939462a06057426ada64bd5a6c99639c898ebaa78146ff7a47607a57bfe7307cb4b042871360f94ba55ef874b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
